yiisoft/queue

config/console.php
src/ExecEvent.php
src/LogBehavior.php
src/drivers/db/Queue.php

Fixed 3.0 db driver and LogBehavior

Fixed 3.0 db driver and LogBehavior

---

src/drivers/db/Queue.php
src/drivers/redis/Queue.php

Fixed redis driver
common.php
```php
'queue' => [
'__class' => \yii\queue\redis\Queue::class,
],
\yii\redis\Connection::class => \yii\di\Reference::to('redis'),
'redis' => [
'__class' => \yii\redis\Connection::class,
],
```

Fixed redis driver

---

config/common.php
config/console.php

fix config

---

composer.json
src/Cli/SignalLoop.php
src/InvalidJobException.php

Adjust composer dependencies and make minor fixes.
[skip ci]
| Tests pass?   | ❌
| Fixed issues  | #28

Some fixes

---

src/Events/JobFailure.php
src/Workers/Worker.php

Fix job failure event method naming

---

src/Queue.php
src/QueueDependentInterface.php

Create an interface for queue-dependent drivers

---

src/Queue.php

Move external dependency to the constructor

---

src/Events/JobFailure.php
tests/unit/WorkerTest.php

Rename stopThrowing to preventThrowing

---

composer.json
config/params.php
src/Commands/ListenCommand.php
src/Commands/RunCommand.php

| Tests pass?   | ✔️
| Fixed issues  | #24

Add console commands

---

composer.json
config/common.php
config/params.php
config/tests.php
src/Command/ListenCommand.php
src/Command/RunCommand.php
src/DriverInterface.php
src/Enum/JobStatus.php
src/Event/AfterExecution.php
src/Event/AfterPush.php
src/Event/BeforeExecution.php
src/Event/BeforePush.php
src/Event/JobFailure.php
src/Exception/InvalidStatusException.php
src/Exception/JobNotSupportedException.php
src/Job/AttemptsRestrictedJob.php
src/Job/CallableJob.php
src/Job/DelayableJobInterface.php
src/Job/JobInterface.php
src/Job/PrioritisedJobInterface.php
src/Job/RetryableJobInterface.php
src/Message.php
src/MessageInterface.php
src/Queue.php
src/Worker/Worker.php
src/Worker/WorkerInterface.php
tests/App/SimpleJob.php
tests/unit/WorkerTest.php

| Is bugfix?    ❌
| New feature?  ❌
| Tests pass?   | ✔️
PR Related to issue #39

Adjust namespaces #39

---

src/Queue.php

Move execution handler to a separate method

---

src/Worker/Worker.php

Worker handler resolving bugfixes

---

composer.json

| Fixed issues  | https://github.com/yiisoft/yii-queue/issues/91

Remove yiisoft/serializer dependency

---

config/common.php
config/tests.php

| Fixed issues  | https://github.com/yiisoft/factory/pull/78

Use new class syntax

---

README.md
config/tests.php
docs/guide/README.md
docs/guide/adapter-list.md
docs/guide/adapter-sync.md
docs/guide/behaviors.md
docs/guide/driver-list.md
docs/guide/migrating-from-yii2-queue.md
docs/guide/usage.md
src/Adapter/AdapterInterface.php
src/Adapter/BehaviorChecker.php
src/Adapter/SynchronousAdapter.php
src/Exception/BehaviorNotSupportedException.php
src/Message/Behaviors/BehaviorInterface.php
src/Message/Behaviors/ExecutableBehaviorInterface.php
src/Queue.php
tests/TestCase.php
tests/Unit/BehaviorCheckerTest.php
tests/Unit/ExceptionTest.php
tests/Unit/QueueDependentInterfaceTest.php
tests/Unit/QueueTest.php
tests/Unit/SynchronousAdapterTest.php

| Fixed issues  | Fix #77
Dependent PR: yiisoft/yii-queue-amqp#28

Fix #77 Rename driver->adapter

---

config/common.php

Fix construct

---

composer.json
src/QueueFactory.php
src/QueueFactoryInterface.php

Adopt to `yiisoft/definitions`

---

composer.json
src/Command/ListenCommand.php
src/Command/RunCommand.php

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Fix console commands

---

src/Adapter/SynchronousAdapter.php
tests/TestCase.php
tests/Unit/SynchronousAdapterTest.php

Fix unit tests

---

composer.json

Use stable yiisoft/definitions package

---

src/Enum/JobStatus.php
src/Exception/InvalidStatusException.php
src/Message/Behaviors/BehaviorInterface.php
src/Queue.php
src/Worker/Worker.php

| Fixed issues  | Fix psalm errors

Fix psalm errors

---

src/Message/Message.php
src/Message/MessageInterface.php
src/Queue.php
src/Worker/Worker.php

Rename MessageInterface.getName to MessageInterface.getHandlerName 

---

src/Queue.php
src/Worker/Worker.php

change logger level for adding to queue and processing of jobs

---

docs/guide/worker.md
src/Command/ListenCommand.php
src/Command/RunCommand.php
tests/Unit/QueueFactoryTest.php
tests/Unit/QueueTest.php
tests/Unit/SynchronousAdapterTest.php
tests/Unit/WorkerTest.php

| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.

Separate chain calls

---

composer.json

Add support for `yiisoft/definitions` version `^2.0`

---

tests/App/FakeHandler.php
tests/Unit/WorkerTest.php

Add test for worker

---

README.md
composer.json

Add support `yiisoft/definitions` version `^3.0`

---

composer.json
psalm.xml
src/Adapter/AdapterInterface.php

Update psalm and fix errors

---

src/Adapter/AdapterInterface.php
src/Middleware/Push/Implementation/DelayMiddlewareInterface.php

Rename $delay => $seconds

---

src/Queue.php

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Fixed the improper variable name usage

---

.dockerignore
.gitattributes

Updated .gitattributes and .dockerignore

---

tests/bootstrap.php

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii-queue/issues/161

update tests folder links

---

tests/Unit/Command/ListenCommandTest.php
tests/Unit/Command/RunCommandTest.php
tests/Unit/Debug/QueueDecoratorTest.php
tests/Unit/Debug/QueueFactoryInterfaceProxyTest.php
tests/Unit/SynchronousAdapterTest.php

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Write tests

---

tests/Unit/Debug/QueueDecoratorTest.php
tests/Unit/Middleware/Consume/ConsumeRequestTest.php
tests/Unit/Middleware/FailureHandling/FailureHandlingRequestTest.php
tests/Unit/Middleware/Push/PushRequestTest.php

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Fixed CloneRemoval mutation tests

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/bc.yml_
.github/workflows/build.yml
.github/workflows/composer-require-checker.yml
.github/workflows/mutation.yml
.github/workflows/rector.yml
.github/workflows/static.yml
.scrutinizer.yml
composer.json
phpunit.xml.dist
rector.php
src/Enum/JobStatus.php
tests/App/FakeHandler.php
tests/TestCase.php
tests/Unit/JobStatusTest.php
tests/Unit/Middleware/Consume/InvalidMiddlewareDefinitionExceptionTest.php
tests/Unit/Middleware/Consume/MiddlewareDispatcherTest.php
tests/Unit/Middleware/Consume/MiddlewareFactoryTest.php
tests/Unit/Middleware/FailureHandling/Implementation/ExponentialDelayMiddlewareTest.php
tests/Unit/Middleware/FailureHandling/Implementation/SendAgainMiddlewareTest.php
tests/Unit/Middleware/FailureHandling/InvalidMiddlewareDefinitionExceptionTest.php
tests/Unit/Middleware/FailureHandling/MiddlewareFactoryTest.php
tests/Unit/Middleware/Push/InvalidMiddlewareDefinitionExceptionTest.php
tests/Unit/Middleware/Push/MiddlewareDispatcherTest.php
tests/Unit/Middleware/Push/MiddlewareFactoryTest.php
tests/Unit/WorkerTest.php

Raise PHP to 8.1

---

README.md

Fix broken link in the readme file

---

docs/guide/en/adapter-list.md

| New feature?  | ✔️
Add new queue adapter for Apache Kafka

Add Apache Kafka to the list of queue adapters

---

docs/guide/en/adapter-list.md

| New feature?  | ✔️
Add new queue adapters for Valkey and Beanstalkd

Add Valkey and Beanstalkd to the list of queue adapters

---

src/QueueFactory.php
tests/Unit/QueueFactoryTest.php

Set channel name to a newly created adapter in QueueFactory

---

.github/workflows/rector.yml
composer.json
rector.php

Fix Rector CI

---

.github/workflows/bechmark.yml

Run benchmark in CI once

---

.github/workflows/build.yml

Fix CodeCov integration

---

src/Debug/QueueCollector.php

Adapt to yiisoft/yii-debug summary

---

src/Middleware/Push/Implementation/IdMiddleware.php
tests/Unit/Middleware/Push/Implementation/IdMiddlewareTest.php

Add a middleware for automatic ID creation for messages before push
